### ISSUE TITLE
DAE file is not read with parse error

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#615]
**Describe the bug**
A specific dae file is not read with a parsing error

**To Reproduce**
 0.  [library_animation_clips.dae.zip](https://github.com/f3d-app/f3d/files/10611465/library_animation_clips.dae.zip)
 1. Open the file using `f3d --dry-run library_animation_clips.dae`

```

Warning: In vtkF3DAssimpImporter.cxx, line 584
vtkF3DAssimpImporter (0x55ddb435eeb0): Assimp failed to load: /home/glow/aur/assimp/src/assimp-5.2.1/test/models/Collada/library_animation_clips.dae


Warning: In vtkF3DAssimpImporter.cxx, line 587
vtkF3DAssimpImporter (0x55ddb435eeb0): Assimp error: Cannot parse string "  0.0 0.0 0.0 1.0  " as a real number: does not start with digit or decimal point followed by digit.


```

**Expected behavior**

![a](https://user-images.githubusercontent.com/3129530/216830136-2fb2286a-dc17-4ffc-8358-951ba6c0d7e3.png)

**System Information:**
 - OS: Linux and Windows

**F3D Information**
Paste the content of `f3d --version`: 1.3.1 and master

**Additional context**
Parts of assimp suite, so I assume it should work with assimp ?

**Comment by shambhupatil** [comment]
Fixed by [this commit](https://github.com/assimp/assimp/pull/5611)

**Comment by mwestphal** [comment]
Thanks for checking @shambhupatil !

**Comment by mwestphal** [comment]
Lets keep this open until assimp do a new release and we can update the superbuild with it.

**Comment by mwestphal** [comment]
I still see a strange artifact but the file is read by assimp correctly 

![a](https://github.com/user-attachments/assets/a6195971-b147-4f73-8690-4b50f15f1562)
