### ISSUE TITLE
VRML files not displayed correctly

### ISSUE THREAD

**Issue by ferrellsl** [f3d-app/f3d#826]
When loading VRML files the models are displayed as incomplete.  Here's an example of how this rabbit model should look:

<img width="810" alt="image" src="https://github.com/f3d-app/f3d/assets/5926287/6809fe22-627d-4841-899e-029c22dc781e">

And here's how it displays in f3d:

<img width="958" alt="image" src="https://github.com/f3d-app/f3d/assets/5926287/e40c8720-e293-4468-b590-30f9b9f4a51d">

This happens with all the VRML models I've tried so far.

**Comment by mwestphal** [comment]
Hi @ferrellsl 

Please share an example VRML.

Thanks !

**Comment by ferrellsl** [comment]
I've also noticed that the missing parts are displayed on the the incorrect side of the model as well.  Both ears on one side of the head and both arms and both legs are on one side of the body.

<img width="956" alt="image" src="https://github.com/f3d-app/f3d/assets/5926287/97a9fcc5-24f5-4087-89ce-41ce87b3a5ce">

Here's the rabbit VERML file


[rabbit.zip](https://github.com/f3d-app/f3d/files/11536185/rabbit.zip)

**Comment by ferrellsl** [comment]
Here's another example of a snowman and how it should appear:
<img width="812" alt="image" src="https://github.com/f3d-app/f3d/assets/5926287/6ec542a0-56e4-4967-b146-90a5974aa213">

but in f3d, it renders like this:

<img width="956" alt="image" src="https://github.com/f3d-app/f3d/assets/5926287/2ddf7cea-895b-4b30-9960-4ccb1c35eed3">

Here's the zip file for the snowman:

[snowman.zip](https://github.com/f3d-app/f3d/files/11536253/snowman.zip)

**Comment by mwestphal** [comment]
Here are examples VRML that works perfectly if that helps:
http://alexei.nfshost.com/3d/virtual.html

Looking at your data it looks like the `Transform`  is not working as expected in vtkVRMLImporter that we use in F3D.
I've opened an issue upstream but I'm not sure VTK devs will look into this as this class is not heavily used considering this bug has been present 8  years in VTK.

FYI @jpouderoux looks like you worked on this in VTK at some point :)

https://gitlab.kitware.com/vtk/vtk/-/issues/18982

**Comment by ferrellsl** [comment]
> Here are examples VRML that works perfectly if that helps @ferrellsl : http://alexei.nfshost.com/3d/virtual.html
> 
> Looking at your data it looks like the `Transform` is not working as expected in vtkVRMLImporter that we use in F3D. I've opened an issue upstream but I'm not sure VTK devs will look into this as this class is not heavily used considering this bug has been present 8 years in VTK.
> 
> FYI @jpouderoux looks like you worked on this in VTK at some point :)
> 
> https://gitlab.kitware.com/vtk/vtk/-/issues/18982

Actually they don't all render perfectly.  This one in particular totally crashes f3d on my system.

http://alexei.nfshost.com/3d/cockranm.wrl

**Comment by mwestphal** [comment]
Indeed, yet another issue in VTK.

https://gitlab.kitware.com/vtk/vtk/-/issues/18983

**Comment by mwestphal** [comment]
Both fixed in VTK and availiable in F3D nightly: https://github.com/f3d-app/f3d/releases/tag/nightly

enjoy @ferrellsl :)

**Comment by ferrellsl** [comment]
Well, that fixed most of the rabbit except its right eye, which stays white.

<img width="1280" alt="image" src="https://github.com/f3d-app/f3d/assets/5926287/19d2a576-2982-43c4-b3a0-c2e57f8304e8">



There's still an issue with geometry and the snowman model.  It still renders improperly.  Arms are missing, colors are missing, and the nose is on the wrong plane and not attached to the face as in the images I shared in my earlier post.


There also seems to be an issue with color space or color gradients.  This lunar crater mmodel should appear like this
<img width="1280" alt="image" src="https://github.com/f3d-app/f3d/assets/5926287/9c386930-7d9c-4604-9d7a-8ed3d9b3ec74">

But gets rendered in green by f3d.

<img width="1280" alt="image" src="https://github.com/f3d-app/f3d/assets/5926287/ee3d899f-55d8-44f0-8921-d25d39e3cd75">

I've attached the lunar crater model
[lunar-crater.zip](https://github.com/f3d-app/f3d/files/11751338/lunar-crater.zip)

**Comment by jpouderoux** [comment]
@ferrellsl Thanks for your report, I will take a look and see if we can fix that easily.

**Comment by mwestphal** [comment]
Any luck with that @jpouderoux ?

**Comment by mwestphal** [comment]
moving to 2.3

**Comment by mwestphal** [comment]
ping @jpouderoux

**Comment by mwestphal** [comment]
In F3D 3.0, no improvement and now snowman actually crashes because we now assume every actors has a mapper, which does not seem to be the case for the VRML importer.

vtkF3DMetaImporter.cxx:241

```
vtkPolyDataMapper::SafeDownCast(actor->GetMapper());
```

**Comment by mwestphal** [comment]
I've created a dedicated issue for my remark above: https://github.com/f3d-app/f3d/issues/1958

I've also update the issue body to improve it.

**Comment by iommu** [comment]
Update for this:
1. [I've fixed F3D](https://github.com/f3d-app/f3d/pull/2934) so that the snowman (or any VRML with extrusions) doesn't crash anymore
2. I'm going to look into VTK now to try and add extrusions which at the very least should make it so that the snowman's arms render  

Additionally, post fix it seems that the snowman is looking a little better at least having black eyes and a blue hat rim. 
<img width="1050" height="687" alt="Image" src="https://github.com/user-attachments/assets/c13dfa61-e8dd-4446-945d-2ef30e5a0e0e" />
I'll see how I go with VTK source code and take a look at the nose and the top hat sections later if I have time 💜

**Comment by iommu** [comment]
Ok so I've finished the initial VTK code which:
* Adds extrusion support (which fixes the snowman arms)
* Fixes a problem where VTK cones are X axis aligned not Y axis (hence the snowman nose rotation)
* Fixes the USE declaration for the "Appearance" node type (which fixes rabbit eye, snowman hat and snowman arm)

Example showing cones before fix :
<img width="4256" height="1721" alt="Image" src="https://github.com/user-attachments/assets/7d1bbe2d-6963-45fb-8c68-3c11cbf2e547" />

After fixes :
<img width="1050" height="687" alt="Image" src="https://github.com/user-attachments/assets/4ead301f-670e-4e73-8e03-e1373a51b353" />

<img width="1050" height="687" alt="Image" src="https://github.com/user-attachments/assets/bf95eec8-197e-4e3d-8d0f-3ab11dfb87d2" />

<img width="1050" height="687" alt="Image" src="https://github.com/user-attachments/assets/79490b3a-4c47-428c-bc81-1fda1b202505" />

I haven't touched VTK before so this might take me a bit to get my changes merged as they'll probably want me to clean it up a lot to make it more VTK-y.

**Comment by snoyer** [comment]
Nice!

Do your changes also happen to fix #1450? According to the screenshots there are some color and transforms bugs your "USE declaration" fixes may have solved, unless there's a whole other set of issues.

> I haven't touched VTK before so this might take me a bit to get my changes merged as they'll probably want me to clean it up a lot to make it more VTK-y.

"they" include @mwestphal, he'll help 👍

**Comment by mwestphal** [comment]
Just open a MR in VTK gitlab and ping me there, Ill assist :)

**Comment by iommu** [comment]
I just took a look at [#1450](https://github.com/f3d-app/f3d/issues/1450). The colors of the components now work. But no the model looks the same. 

I'll try at it a bit more.

**Comment by iommu** [comment]
Of note with this however. As VRML is a very CAD-centric format maybe adding support for a more "official" OCCT based importer might be a good idea. For reference it seems to support fully all of the examples in this tread, including that horrifying animated cockroach. 

Does (lib)F3D support the concept of multiple importers for a single file? Maybe even switching between them.

**Comment by mwestphal** [comment]
> Of note with this however. As VRML is a very CAD-centric format maybe adding support for a more "official" OCCT based importer might be a good idea. For reference it seems to support fully all of the examples in this tread, including that horrifying animated cockroach.
> 
> Does (lib)F3D support the concept of multiple importers for a single file? Maybe even switching between them.

Yes, we can have multiple readers for the same extension. If you want to give a go to using OCCT for vrml, you are very welcome to do so.

**Comment by iommu** [comment]
I managed to get it working quite quickly, but as far as I can tell, the way colors are hashed doesn't quite work for the OCCT VRML reader. But mesh wise the reader is a lot faster and is accurate.

<img width="1050" height="687" alt="Image" src="https://github.com/user-attachments/assets/4fdbc111-72d5-48b6-99f5-b6f99fe64d34" />

**Comment by snoyer** [comment]
Mayo manages to retrieve some of the colors but not all
<img width="669" height="553" alt="Image" src="https://github.com/user-attachments/assets/e1d78662-59df-4ac5-80b2-d17bd480de00" />

I'd like to believe the colors are all in there and it's just a matter of discovering what quirky way OCCT expects you to retrieve them (which is what we had to do for the other OCCT formats)

Do you have a branch we can look at?

**Comment by mwestphal** [comment]
> I managed to get it working quite quickly, but as far as I can tell, the way colors are hashed doesn't quite work for the OCCT VRML reader. But mesh wise the reader is a lot faster and is accurate.
> <img alt="Image" width="1050" height="687" src="https://private-user-images.githubusercontent.com/11268243/567373803-4fdbc111-72d5-48b6-99f5-b6f99fe64d34.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzQxNjI0NDgsIm5iZiI6MTc3NDE2MjE0OCwicGF0aCI6Ii8xMTI2ODI0My81NjczNzM4MDMtNGZkYmMxMTEtNzJkNS00OGI2LTk5ZjUtYjZmOTlmZTY0ZDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzIyVDA2NDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmM2U0OWM0NTQxNDZmODAyM2ZlNWQ2ZTNiZDQ4MzRjNDc1MDQzNjk3OTE0NTU3ZTIwMjc4NGQ4MDVmNzE4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ri4FL4TGlK-fFFO4YlyZPIBWxs3P-np8iqb5Xt3qnko">

keep in mind the OCCTReader is a reader, not an importer, so if you recover colors they must be define at data on each point and not on the actors, contrary to the VRMLImporter.

**Comment by iommu** [comment]
Branch is [here](https://github.com/iommu/f3d/tree/occt_vrml_reader).
Thank you, I haven't heard of Mayo before, but after playing around with the raw OCCT VRML importer it seems have quite a few quirks of it's own. 
* Does not support cones
* Does not support extrusions
* Seems to miss some color data
* The parser seems to fail fairly frequently
* Doesn't support animations  

A bit disappointing, I was hoping the OCCT parser was what FreeCAD was using under the hood as it's parser seems to be the gold standard ATM, but after some further searching on their forums it seems it may be https://www.coin3d.org/ 

Running some of their examples using pivy seems to back this up.
<img width="1131" height="978" alt="Image" src="https://github.com/user-attachments/assets/f4f131b7-66b0-4183-b69e-8124b1f9812b" />

I can take a cursory look into seeing if I can add this import to f3d if you would like. The main benefit would be proper support for KiCAD's VRML files. But it would add an extra dependency.

**Comment by mwestphal** [comment]
I'm not fully against it but adding a new dependency for a format we already support is not the best, it would have to be easy to build, deploy and better in all point than VTK implementation. If it gives access to other formats we dont support yet, then it woudl justify it more :)

**Comment by iommu** [comment]
The code quality of this initial fix is terrifying. But it does work, using only modifications to the VTK parser, no 3rd party 🥳 
Long story short:
* VTK parser didn't support the DEF/USE operatives for Transform, which should effectively duplicate all of the enclosed child geometry.
* VTK processed transform fields in order, i.e. a Transform with {translation, rotation} evaluates different to a Transform with {rotation, translation}

<img width="1050" height="687" alt="Image" src="https://github.com/user-attachments/assets/55e9d48b-499a-4810-b53d-d70822c424bc" />

<img width="1050" height="687" alt="Image" src="https://github.com/user-attachments/assets/00e917be-0803-4734-adb4-a85059e1c63d" />

I'm going to clean this up and try get this merged at the same time as all the other fixes if I can. For my Kicad is the main program I know of (& use) which uses VRML files. So for me supporting it's outputs is a high priority.

**Comment by mwestphal** [comment]
> So for me supporting it's outputs is a high priority.

Definitely agree on that, thanks a lot for your work.

**Comment by mwestphal** [comment]
Need any help moving forward @iommu ?

**Comment by iommu** [comment]
This code should be merged into VTK now as of https://gitlab.kitware.com/vtk/vtk/-/merge_requests/13052 as should [#1450](https://github.com/f3d-app/f3d/issues/1450)

**Comment by mwestphal** [comment]
indeed! Ill take care of the update.

**Comment by mwestphal** [comment]
Rabbit is now perfect in latest nightly! https://github.com/f3d-app/f3d/releases/tag/nightly

<img width="1000" height="600" alt="Image" src="https://github.com/user-attachments/assets/3935bf36-3d48-4e3c-9e57-235583396617" />

Snowman however seems to have melted away in the process ? 

<img width="1000" height="600" alt="Image" src="https://github.com/user-attachments/assets/0e52b1cb-a99d-4177-a12a-3f2432b4289f" />

Any idea @iommu

**Comment by mwestphal** [comment]
Unassigning myself, investigation needed :)
